import { useCallback } from "react";
import { SEVERITY_ORDER } from "../utils/severityHelpers";

/**
 * Custom hook for exporting scan results as a report.
 */
export function useExport(domain, findings) {
  const generateReport = useCallback(() => {
    const now = new Date();
    const dateStr = now.toISOString().replace("T", " ").substring(0, 19);

    const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    findings.forEach((f) => {
      if (counts[f.severity] !== undefined) counts[f.severity]++;
    });

    let report = `NETMAP SECURITY REPORT
Generated: ${dateStr}
Target: ${domain}
${"━".repeat(50)}

EXECUTIVE SUMMARY
${"─".repeat(50)}
Total Assets:  ${findings.length}
Critical:      ${counts.critical}
High:          ${counts.high}
Medium:        ${counts.medium}
Low:           ${counts.low}
Info:          ${counts.info}

FINDINGS
${"─".repeat(50)}
`;

    // Sort findings by severity
    const sorted = [...findings].sort(
      (a, b) =>
        SEVERITY_ORDER.indexOf(a.severity) -
        SEVERITY_ORDER.indexOf(b.severity)
    );

    sorted.forEach((f) => {
      report += `
[${f.severity.toUpperCase()}] ${f.title}
  Host:    ${f.host}
  What:    ${f.description}
  Action:  ${f.action}
`;
    });

    report += `
${"━".repeat(50)}
Report generated by NetMap · Attack Surface Mapper
`;

    return report;
  }, [domain, findings]);

  const downloadReport = useCallback(() => {
    const report = generateReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const dateStr = new Date().toISOString().split("T")[0];
    a.href = url;
    a.download = `netmap-report-${domain}-${dateStr}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [domain, generateReport]);

  const copySummary = useCallback(async () => {
    const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    findings.forEach((f) => {
      if (counts[f.severity] !== undefined) counts[f.severity]++;
    });

    const summary = `NetMap Report — ${domain}
${counts.critical} Critical · ${counts.high} High · ${counts.medium} Medium · ${counts.low} Low
Top Issues:
${findings
  .filter((f) => f.severity === "critical" || f.severity === "high")
  .map((f) => `• [${f.severity.toUpperCase()}] ${f.title} — ${f.host}`)
  .join("\n")}`;

    try {
      await navigator.clipboard.writeText(summary);
      return true;
    } catch {
      return false;
    }
  }, [domain, findings]);

  return { downloadReport, copySummary, generateReport };
}
