import { useCallback } from "react";
import { SEVERITY_ORDER } from "../utils/severityHelpers";

export function useExport(domain, findings) {
  const generateReport = useCallback(() => {
    const now = new Date();
    const dateStr = now.toISOString().replace("T", " ").substring(0, 19);

    const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    findings.forEach((f) => {
      const sev = f.severity?.toLowerCase();
      if (counts[sev] !== undefined) counts[sev]++;
    });

    const uniqueHosts = [...new Set(findings.map((f) => f.host))];

    let report = `NETMAP SECURITY REPORT
${"━".repeat(50)}
Target:     ${domain}
Generated:  ${dateStr}
Total:      ${findings.length} findings | ${uniqueHosts.length} assets

SEVERITY SUMMARY
${"─".repeat(50)}
Critical:      ${counts.critical}
High:          ${counts.high}
Medium:        ${counts.medium}
Low:           ${counts.low}
Info:          ${counts.info}

CRITICAL / HIGH FINDINGS
${"─".repeat(50)}
`;

    const sorted = [...findings].sort(
      (a, b) =>
        SEVERITY_ORDER.indexOf(a.severity?.toLowerCase()) -
        SEVERITY_ORDER.indexOf(b.severity?.toLowerCase())
    );

    sorted.forEach((f) => {
      report += `
[${(f.severity || "INFO").toUpperCase()}] ${f.title}
  Host:    ${f.host}${f.port ? `\n  Port:    ${f.port}` : ""}
  Source:  ${f.source || "—"}
  Action:  ${f.action}
`;
    });

    report += `
${"━".repeat(50)}
Report generated by NetMap · Attack Surface Intelligence
`;

    return report;
  }, [domain, findings]);

  const downloadReport = useCallback(() => {
    const report = generateReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const dateStr = new Date().toISOString().split("T")[0];
    a.href = url;
    a.download = `netmap-report-${domain}-${dateStr}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [domain, generateReport]);

  const copySummary = useCallback(async () => {
    const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    findings.forEach((f) => {
      const sev = f.severity?.toLowerCase();
      if (counts[sev] !== undefined) counts[sev]++;
    });

    const uniqueHosts = [...new Set(findings.map((f) => f.host))];

    const topFindings = findings
      .filter((f) => f.severity === "critical" || f.severity === "high")
      .slice(0, 5)
      .map((f) => `• [${f.severity.toUpperCase()}] ${f.title} — ${f.host}`)
      .join("\n");

    const summary = `NetMap Security Report — ${domain}
${uniqueHosts.length} assets scanned · ${findings.length} findings

${counts.critical} Critical · ${counts.high} High · ${counts.medium} Medium · ${counts.low} Low

Top Issues:
${topFindings}

Generated by NetMap · netmap.io`;

    try {
      await navigator.clipboard.writeText(summary);
      return true;
    } catch {
      return false;
    }
  }, [domain, findings]);

  return { downloadReport, copySummary, generateReport };
}
