import express from "express";
import cors from "cors";
import { spawn } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());

// Health check
app.get("/api/health", (req, res) => res.send("OK"));

// The SSE endpoint for running the scan and streaming logs
app.get("/api/scan", (req, res) => {
  const domain = req.query.domain;
  if (!domain || !/^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+|^[a-zA-Z0-9.-]+$/.test(domain)) {
    return res.status(400).json({ error: "Invalid or missing domain parameter" });
  }

  // Support frontend Server-Sent Events
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();

  // Send an initial connected event
  res.write(`data: ${JSON.stringify({ type: "connected", message: `Connected to scanner backend for ${domain}` })}\n\n`);

  // We are running the pipeline from the parent directory where pipeline.py lives
  const pythonScriptDir = path.join(__dirname, "..");
  const pythonScriptPath = path.join(pythonScriptDir, "pipeline.py");

  // Spawn the child process: python pipeline.py <domain> --json --demo --workers 30 --no-nmap --no-nuclei
  const child = spawn("python", [pythonScriptPath, domain, "--json", "--demo", "--workers", "30", "--no-nmap", "--no-nuclei"], {
    cwd: pythonScriptDir,
    env: {
      ...process.env,
      PYTHONUNBUFFERED: "1",
      PYTHONIOENCODING: "utf-8",
    },
  });

  let isClosed = false;

  req.on("close", () => {
    isClosed = true;
    if (!child.killed) {
      console.log("Client disconnected, killing scanner child process...");
      try {
        child.kill("SIGTERM");
      } catch (err) {
        console.error("Error killing child process:", err);
      }
    }
  });

  child.on("error", (err) => {
    console.error("Child process error:", err);
  });

  // Handle standard output logs
  child.stdout.on("data", (data) => {
    if (isClosed) return;
    const lines = data.toString().split(/\r?\n/);
    for (const line of lines) {
      if (line.trim().length > 0) {
        // Strip ANSI color codes to render cleanly on frontend
        const cleanLine = line.replace(/\x1b\[[0-9;]*m/g, "");
        
        let type = "info";
        if (cleanLine.includes("[ERROR]") || cleanLine.includes("[WARN]")) type = "error";
        if (cleanLine.includes("✔") || cleanLine.includes("complete")) type = "success";
        
        const payload = JSON.stringify({ type, message: cleanLine });
        res.write(`data: ${payload}\n\n`);
      }
    }
  });

  // Handle error output (Python logger writes everything to stderr by default)
  child.stderr.on("data", (data) => {
    if (isClosed) return;
    const lines = data.toString().split(/\r?\n/);
    for (const line of lines) {
      if (line.trim().length > 0) {
        const cleanLine = line.replace(/\x1b\[[0-9;]*m/g, "");
        
        let type = "error";
        if (cleanLine.includes("[INFO]")) type = "info";
        if (cleanLine.includes("[WARN]")) type = "error";
        if (cleanLine.includes("✔") || cleanLine.includes("complete")) type = "success";
        
        const payload = JSON.stringify({ type, message: cleanLine });
        res.write(`data: ${payload}\n\n`);
      }
    }
  });

  // When process finishes
  child.on("close", (code) => {
    if (isClosed) return;
    
    const payload = JSON.stringify({ type: "process_exit", message: `Scan process exited with code ${code}` });
    res.write(`data: ${payload}\n\n`);

    // Look for the JSON file generated by pipeline.py
    const cleanDomain = domain.replace(/\./g, "_");
    const jsonFileName = `${cleanDomain}_findings.json`;
    const jsonFilePath = path.join(pythonScriptDir, jsonFileName);

    let findings = [];
    if (fs.existsSync(jsonFilePath)) {
      try {
        const fileContent = fs.readFileSync(jsonFilePath, "utf-8");
        findings = JSON.parse(fileContent);
      } catch (err) {
        console.error("Failed to parse findings JSON:", err);
      }
    }

    // Send final event with findings
    res.write(`data: ${JSON.stringify({ type: "done", findings })}\n\n`);
    res.end();
  });
});

const PORT = 3001;
app.listen(PORT, () => {
  console.log(`Backend API running on http://localhost:${PORT}`);
});
